createDeployment: true
createRoute: true
extraLabels:
command:
args:
initContainers:
containerPortName:
containerPort:
quayOrg: "doliveira1277"
quayRepo: ""
tag:
customImage:
resources:
hpaMemoryLimit:
hpaCPULimit:
replicas: 
hpaMinReplicaCount:
hpaMaxReplicaCount:
externalSecret:
extraSecrets:
ingressHost:
ingressClassName:
ingressAnnotations:
ingressPaths:
job:
  create: false
  customImage:
  backoffLimit: 1
  command:
  volumeMounts:
  volumes:
  envFrom:
secret:
  create: false
  data:
configMap:
  create: false
  data:
