{{- if .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
{{- toYaml .Values.configMap.data | nindent 2 }}
{{- end }}
