{{- if .Values.job.create }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-job
  {{- if .Values.job.annotations }}
  annotations:
  {{- toYaml .Values.job.annotations | nindent 4 }}
  {{- end }}
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  template:
    spec:
      containers:
        - name: {{ .Release.Name }}-job
          {{- if .Values.job.customImage }}
          image: {{ .Values.job.customImage }}
          {{- else }}
          image: quay.io/fedora/httpd-24-micro
          {{- end }}
          command: 
          {{- toYaml .Values.job.command | nindent 12 }}
          {{- if .Values.job.volumeMounts }}
          volumeMounts:
          {{- toYaml .Values.job.volumeMounts | nindent 12 }}
          {{- end }}
          {{- if .Values.job.envFrom }}
          envFrom:
          {{- toYaml .Values.job.envFrom | nindent 12 }}
          {{- end }}
      restartPolicy: Never
      {{- if .Values.job.volumeMounts }}
      volumes:
      {{- toYaml .Values.job.volumes | nindent 8 }}
      {{- end }}
{{ end }}
