{{- if .Values.createRoute }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name  }}
  namespace: {{ .Release.Namespace }}
spec:
  port:
    targetPort: {{ .Values.containerPort | default 8080 }}
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ .Release.Name  }}
    weight: 100
{{ end }}
