{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }} 
  {{- if .Values.secret.annotations }}
  annotations:
  {{- toYaml .Values.secret.annotations | nindent 4 }}
  {{- end }}
stringData:
{{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}
