{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }} 
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
stringData:
{{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}
